#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /run/tar1090
sleep 5

srcdir=/run/readsb
service=readsb

/usr/local/share/tar1090/tar1090.sh \
  "/run/$service" \
  "$srcdir" \
  2>&1 | mawk -W interactive '{print "[tar1090] " $0}'
