#!/usr/bin/with-contenv bash
# shellcheck shell=bash

{
  echo "SOURCE=/var/readsb/readsb"
  echo "INTERVAL=${TIME_INTERVAL:=10}"
  echo "HISTORY=${TIME_HISTORY:=24}"
  echo "CHUNK_SIZE=${TIME_CHUNK_SIZE:=240}"
} > /etc/default/timelapse1090

/usr/local/share/timelapse1090/timelapse1090.sh \
  2>&1 | mawk -W interactive '{print "[timelapse1090] " $0}'

sleep 30
