#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Define bash colours
NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'
#CYAN='\033[0;36m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEAST_HOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e LAT"
if [ -z "${LAT}" ]; then
  echo -e "${LIGHTRED}ERROR: LAT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e LON"
if [ -z "${LON}" ]; then
  echo -e "${LIGHTRED}ERROR: LON environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ $EXITCODE == 0 ]; then
  echo -e "${CYAN}INFO: Connect to $BEAST_HOST${NOCOLOR}"
fi

exit $EXITCODE
