#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /srv/tar1090-db || exit 1

if [ "${UPDATE_TAR1090}" = "true" ]; then 
	# Attempt to update tar1090 database
	git fetch --depth 1 origin master > /dev/null 2>&1 || exit 0
	git reset --hard origin/master > /dev/null 2>&1 || exit 0
fi

# Print tar1090 database version
DB_VERSION=$(git rev-parse --short HEAD)
echo "tar1090 database version: ${DB_VERSION}"
export DB_VERSION

cd /srv/tar1090 || exit 1

if [ "${UPDATE_TAR1090}" = "true" ]; then 
	# Attempt to update tar1090
	git fetch origin master > /dev/null 2>&1 || exit 0
	git reset --hard origin/master > /dev/null 2>&1 || exit 0
fi

# Print tar1090 version
TAR_VERSION=$(git rev-parse --short HEAD)
echo "tar1090 version: ${TAR_VERSION}"
export TAR_VERSION
