#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Modify nginx.conf
srcdir=/run/readsb
service=readsb
html_path=/usr/local/share/tar1090/html

# Modify 88-tar1090.conf
sed -i.original \
  -e "s?SOURCE_DIR?$srcdir?g" \
  -e "s?SERVICE?$service?g" \
  -e "s?/INSTANCE/?/?g" \
  -e "s?/INSTANCE??g" \
  -e "s?HTMLPATH?$html_path?g" \
  /usr/local/share/tar1090/nginx.conf

sed -i '/location \/data\/ {/a \ \ access_log off;' \
  /usr/local/share/tar1090/nginx.conf
