#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Vars
srcdir=/run/readsb
service=readsb
html_path=/usr/local/share/tar1090/html

# Modify 88-tar1090.conf
sed -i.original \
  -e "s?SOURCE_DIR?$srcdir?g" \
  -e "s?SERVICE?$service?g" \
  -e "s?/INSTANCE/?/?g" \
  -e "s?/INSTANCE??g" \
  -e "s?HTMLPATH?$html_path?g" \
  /usr/local/share/tar1090/88-tar1090.conf

# Link to lighttpd configuration
ln -snf /usr/local/share/tar1090/88-tar1090.conf /etc/lighttpd/conf-enable/88-tar1090.conf

# Modify tar1090 settings
sed -i.original \
  -e 's/skyview978/skyaware978/' \
  /usr/local/share/tar1090/default
