#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Modify tar1090 settings
sed -i.original \
  -e 's/skyview978/skyaware978/' \
  /usr/local/share/tar1090/default

if [ -z "${TAR_INTERVAL}" ]; then
  echo "5" > /var/run/s6/container_environment/TAR_INTERVAL
fi

