#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Vars
html_path=/usr/local/share/tar1090/html

# Rename database
mv "$html_path/db" "/usr/local/share/tar1090/html/db-${DB_VERSION}"

# Update with renamed database path
sed -i \
  "s/<script>let databaseFolder =.*<\/script>/<script>let databaseFolder = \"db-${DB_VERSION}\"<\/script>/g" \
  "$html_path/index.html"

# Write version.json
echo "{ \"tar1090Version\": \"$TAR_VERSION\", \"databaseVersion\": \"$DB_VERSION\" }" > \
    "$html_path/version.json"

# Update in index.html
sed -i -e "s/tar1090 on github/tar1090 on github ($(date +%y%m%d))/" \
  "$html_path/index.html"

# Rename Files
mv "$html_path/dbloader.js" "$html_path/dbloader_$TAR_VERSION.js"
mv "$html_path/defaults.js" "$html_path/defaults_$TAR_VERSION.js"
mv "$html_path/early.js" "$html_path/early_$TAR_VERSION.js"
mv "$html_path/flags.js" "$html_path/flags_$TAR_VERSION.js"
mv "$html_path/formatter.js" "$html_path/formatter_$TAR_VERSION.js"
mv "$html_path/layers.js" "$html_path/layers_$TAR_VERSION.js"
mv "$html_path/markers.js" "$html_path/markers_$TAR_VERSION.js"
mv "$html_path/planeObject.js" "$html_path/planeObject_$TAR_VERSION.js"
mv "$html_path/registrations.js" "$html_path/registrations_$TAR_VERSION.js"
mv "$html_path/script.js" "$html_path/script_$TAR_VERSION.js"
mv "$html_path/style.css" "$html_path/style_$TAR_VERSION.css"

# Update in index
sed -i \
    -e "s/dbloader.js/dbloader_$TAR_VERSION.js/" \
    -e "s/defaults.js/defaults_$TAR_VERSION.js/" \
    -e "s/early.js/early_$TAR_VERSION.js/" \
    -e "s/flags.js/flags_$TAR_VERSION.js/" \
    -e "s/formatter.js/formatter_$TAR_VERSION.js/" \
    -e "s/layers.js/layers_$TAR_VERSION.js/" \
    -e "s/markers.js/markers_$TAR_VERSION.js/" \
    -e "s/planeObject.js/planeObject_$TAR_VERSION.js/" \
    -e "s/registrations.js/registrations_$TAR_VERSION.js/" \
    -e "s/script.js/script_$TAR_VERSION.js/" \
    -e "s/style.css/style_$TAR_VERSION.css/" \
    "$html_path/index.html"
