#!/usr/bin/with-contenv bash
# shellcheck shell=bash

sed -i -e "/^[ \t]*<body.*/a<div class=\"infoBlockTitleText link\" style=\"text-align: center\"><a href=\"/timelapse1090/\">Timelapse1090</a> | <a href=\"/graphs1090/\">Graphs1090</a></div>\n" /usr/local/share/tar1090/html/index.html
sed -i -e "/^[ \t]*<body.*/a<div class=\"infoBlockTitleText link\" style=\"text-align: center\"><a href=\"/\">Tar1090</a> | <a href=\"/graphs1090/\">Graphs1090</a></div>\n" /usr/local/share/timelapse1090/html/index.html
sed -i -e "/^[ \t]*<body.*/a<div class=\"infoBlockTitleText link\" style=\"text-align: center\"><a href=\"/\">Tar1090</a> | <a href=\"/timelapse1090/\">Timelapse1090</a></div>\n" /usr/local/share/graphs1090/html/index.html

# TAR1090 ENV VARS
printf "%s" "${TAR_INTERVAL:=8}" > /var/run/s6/container_environment/INTERVAL
printf "%s" "${TAR_HISTORY_SIZE:=450}" > /var/run/s6/container_environment/HISTORY_SIZE
printf "%s" "${TAR_GZIP_LVL:=3}" > /var/run/s6/container_environment/GZIP_LVL
printf "%s" "${TAR_PTRACKS:=8}" > /var/run/s6/container_environment/PTRACKS
printf "%s" "${TAR_CHUNK_SIZE:=20}" > /var/run/s6/container_environment/CHUNK_SIZE

# TAR1090 JS VARS 
if [[ -n "$TAR_TITLE" ]]; then
  printf "%s" "PageName = ${TAR_TITLE};" > /usr/local/share/tar1090/html/config.js
fi
if [[ -n "$TAR_NBPLANEINTITLE" ]]; then
  printf "%s" "PlaneCountInTitle = ${TAR_NBPLANEINTITLE};" > /usr/local/share/tar1090/html/config.js
fi
if [[ -n "$TAR_MSGRATEINTITLE" ]]; then
  printf "%s" "MessageRateInTitle = ${TAR_MSGRATEINTITLE};" > /usr/local/share/tar1090/html/config.js
fi
if [[ -n "$TAR_UNITS" ]]; then
  printf "%s" "DisplayUnits = ${TAR_UNITS};" > /usr/local/share/tar1090/html/config.js
fi




# TIMELAPSE1090 JS VARS
if [[ -n "$TAR_NBPLANEINTITLE" ]]; then
  printf "%s" "PlaneCountInTitle = ${TAR_NBPLANEINTITLE};" > /usr/local/share/timelapse1090/html/config.js
fi
if [[ -n "$TAR_MSGRATEINTITLE" ]]; then
  printf "%s" "MessageRateInTitle = ${TAR_MSGRATEINTITLE};" > /usr/local/share/timelapse1090/html/config.js
fi
if [[ -n "$TAR_UNITS" ]]; then
  printf "%s" "DisplayUnits = ${TAR_UNITS};" > /usr/local/share/timelapse1090/html/config.js
fi



#printf "${TAR_PF_ENABLE:=0}" > /var/run/s6/container_environment/PF_ENABLE
#printf "${TAR_PF_URL:=http://127.0.0.1:30053/ajax/aircraft}" > /var/run/s6/container_environment/PF_URL
